######################################################################
# Automatically generated by qmake (2.01a) jeu. mars 26 16:16:47 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

QT += phonon

OBJECTS_DIR = build/
MOC_DIR = build/

# Input
HEADERS += src/Engine.h src/MehdiaPlayer.h src/UI.h src/UIPlaylist.h src/UIFolder.h src/UIControl.h src/UISettings.h src/MehdiaPlayer_VideoWidget.h
SOURCES += src/Engine.cpp src/main.cpp  src/MehdiaPlayer.cpp src/UI.cpp src/UIPlaylist.cpp src/UIFolder.cpp src/UIControl.cpp src/UISettings.cpp src/MehdiaPlayer_VideoWidget.cpp
